name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_CONNECTION_STRING: '"UseDevelopmentStorage=true;"'
    strategy:
      matrix:
        php-versions:
          - '8.2'
    steps:
      - uses: actions/checkout@v2
      - run: composer install --prefer-dist -o
      - run: ./vendor/bin/phpunit -c phpunit.local.xml.dist
